// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetHealth():Promise<main.Health>;

export function GetRecentEvents():Promise<Array<main.AppEvent>>;

export function GetSettings():Promise<main.Settings>;

export function SaveSettings(arg1:main.SaveSettingsInput):Promise<main.Settings>;
