// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeJobDescription(arg1) {
  return window['go']['main']['App']['AnalyzeJobDescription'](arg1);
}

export function AutoSelectResumeBullets(arg1) {
  return window['go']['main']['App']['AutoSelectResumeBullets'](arg1);
}

export function BuildJobMatchMap(arg1) {
  return window['go']['main']['App']['BuildJobMatchMap'](arg1);
}

export function BuildResumeContext(arg1) {
  return window['go']['main']['App']['BuildResumeContext'](arg1);
}

export function CreateBlockedClaim(arg1) {
  return window['go']['main']['App']['CreateBlockedClaim'](arg1);
}

export function CreateCandidateSource(arg1) {
  return window['go']['main']['App']['CreateCandidateSource'](arg1);
}

export function CreateJobDescription(arg1) {
  return window['go']['main']['App']['CreateJobDescription'](arg1);
}

export function DeleteAllCandidateClaims() {
  return window['go']['main']['App']['DeleteAllCandidateClaims']();
}

export function DeleteAllEvidenceFacts() {
  return window['go']['main']['App']['DeleteAllEvidenceFacts']();
}

export function DeleteBlockedClaim(arg1) {
  return window['go']['main']['App']['DeleteBlockedClaim'](arg1);
}

export function DeleteCandidateClaim(arg1) {
  return window['go']['main']['App']['DeleteCandidateClaim'](arg1);
}

export function DeleteCandidateSource(arg1) {
  return window['go']['main']['App']['DeleteCandidateSource'](arg1);
}

export function DeleteEvidenceFact(arg1) {
  return window['go']['main']['App']['DeleteEvidenceFact'](arg1);
}

export function DeleteJobDescription(arg1) {
  return window['go']['main']['App']['DeleteJobDescription'](arg1);
}

export function DeleteSourceSection(arg1) {
  return window['go']['main']['App']['DeleteSourceSection'](arg1);
}

export function DeleteTailoredBulletDraft(arg1) {
  return window['go']['main']['App']['DeleteTailoredBulletDraft'](arg1);
}

export function DetectSourceSections(arg1) {
  return window['go']['main']['App']['DetectSourceSections'](arg1);
}

export function DraftCandidateProfileFromSource(arg1) {
  return window['go']['main']['App']['DraftCandidateProfileFromSource'](arg1);
}

export function ExtractEvidenceFacts(arg1) {
  return window['go']['main']['App']['ExtractEvidenceFacts'](arg1);
}

export function GenerateApplicationStrategy(arg1) {
  return window['go']['main']['App']['GenerateApplicationStrategy'](arg1);
}

export function GenerateCandidateClaims() {
  return window['go']['main']['App']['GenerateCandidateClaims']();
}

export function GenerateFitAnalysis(arg1) {
  return window['go']['main']['App']['GenerateFitAnalysis'](arg1);
}

export function GenerateTailoredBulletDrafts(arg1) {
  return window['go']['main']['App']['GenerateTailoredBulletDrafts'](arg1);
}

export function GetApplicationStrategy(arg1) {
  return window['go']['main']['App']['GetApplicationStrategy'](arg1);
}

export function GetCandidateProfile() {
  return window['go']['main']['App']['GetCandidateProfile']();
}

export function GetContextAgentRun(arg1) {
  return window['go']['main']['App']['GetContextAgentRun'](arg1);
}

export function GetFitAnalysis(arg1) {
  return window['go']['main']['App']['GetFitAnalysis'](arg1);
}

export function GetHealth() {
  return window['go']['main']['App']['GetHealth']();
}

export function GetJobAnalysis(arg1) {
  return window['go']['main']['App']['GetJobAnalysis'](arg1);
}

export function GetRecentEvents() {
  return window['go']['main']['App']['GetRecentEvents']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetToolStatus() {
  return window['go']['main']['App']['GetToolStatus']();
}

export function ImportCandidateSourceFile(arg1) {
  return window['go']['main']['App']['ImportCandidateSourceFile'](arg1);
}

export function InstallTectonic() {
  return window['go']['main']['App']['InstallTectonic']();
}

export function ListBlockedClaims() {
  return window['go']['main']['App']['ListBlockedClaims']();
}

export function ListBulletGenerationEvents(arg1) {
  return window['go']['main']['App']['ListBulletGenerationEvents'](arg1);
}

export function ListCandidateClaims(arg1) {
  return window['go']['main']['App']['ListCandidateClaims'](arg1);
}

export function ListCandidateSources() {
  return window['go']['main']['App']['ListCandidateSources']();
}

export function ListContextAgentRuns(arg1) {
  return window['go']['main']['App']['ListContextAgentRuns'](arg1);
}

export function ListContextAgentSteps(arg1) {
  return window['go']['main']['App']['ListContextAgentSteps'](arg1);
}

export function ListEvidenceFacts(arg1) {
  return window['go']['main']['App']['ListEvidenceFacts'](arg1);
}

export function ListJobDescriptions() {
  return window['go']['main']['App']['ListJobDescriptions']();
}

export function ListJobFactMatches(arg1) {
  return window['go']['main']['App']['ListJobFactMatches'](arg1);
}

export function ListJobRequirements(arg1) {
  return window['go']['main']['App']['ListJobRequirements'](arg1);
}

export function ListPromptResearchSources() {
  return window['go']['main']['App']['ListPromptResearchSources']();
}

export function ListPromptRules() {
  return window['go']['main']['App']['ListPromptRules']();
}

export function ListSourceSections(arg1) {
  return window['go']['main']['App']['ListSourceSections'](arg1);
}

export function ListTailoredBulletDrafts(arg1) {
  return window['go']['main']['App']['ListTailoredBulletDrafts'](arg1);
}

export function ParseJobDescription(arg1) {
  return window['go']['main']['App']['ParseJobDescription'](arg1);
}

export function RenderSamplePDF() {
  return window['go']['main']['App']['RenderSamplePDF']();
}

export function SaveAPIKey(arg1) {
  return window['go']['main']['App']['SaveAPIKey'](arg1);
}

export function SaveCandidateProfile(arg1) {
  return window['go']['main']['App']['SaveCandidateProfile'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectTailoredBulletDraft(arg1) {
  return window['go']['main']['App']['SelectTailoredBulletDraft'](arg1);
}

export function StartContextAgent(arg1) {
  return window['go']['main']['App']['StartContextAgent'](arg1);
}

export function TestLLM() {
  return window['go']['main']['App']['TestLLM']();
}

export function UpdateBlockedClaim(arg1) {
  return window['go']['main']['App']['UpdateBlockedClaim'](arg1);
}

export function UpdateCandidateClaimReview(arg1) {
  return window['go']['main']['App']['UpdateCandidateClaimReview'](arg1);
}

export function UpdateEvidenceFactReview(arg1) {
  return window['go']['main']['App']['UpdateEvidenceFactReview'](arg1);
}

export function UpdateJobDescription(arg1) {
  return window['go']['main']['App']['UpdateJobDescription'](arg1);
}

export function UpdatePromptRule(arg1) {
  return window['go']['main']['App']['UpdatePromptRule'](arg1);
}

export function UpdateSourceSection(arg1) {
  return window['go']['main']['App']['UpdateSourceSection'](arg1);
}

export function UpdateTailoredBulletDraft(arg1) {
  return window['go']['main']['App']['UpdateTailoredBulletDraft'](arg1);
}
