// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateCandidateSource(arg1:main.CreateCandidateSourceInput):Promise<main.CandidateSource>;

export function DeleteCandidateSource(arg1:main.DeleteInput):Promise<void>;

export function DeleteEvidenceFact(arg1:main.DeleteInput):Promise<void>;

export function DeleteSourceSection(arg1:main.DeleteInput):Promise<void>;

export function DetectSourceSections(arg1:number):Promise<Array<main.SourceSection>>;

export function DraftCandidateProfileFromSource(arg1:number):Promise<main.CandidateProfile>;

export function ExtractEvidenceFacts(arg1:main.ExtractEvidenceFactsInput):Promise<Array<main.EvidenceFact>>;

export function GetCandidateProfile():Promise<main.CandidateProfile>;

export function GetHealth():Promise<main.Health>;

export function GetRecentEvents():Promise<Array<main.AppEvent>>;

export function GetSettings():Promise<main.Settings>;

export function GetToolStatus():Promise<main.ToolStatus>;

export function ImportCandidateSourceFile(arg1:main.ImportCandidateSourceFileInput):Promise<main.CandidateSource>;

export function InstallTectonic():Promise<main.InstallTectonicResult>;

export function ListCandidateSources():Promise<Array<main.CandidateSource>>;

export function ListEvidenceFacts(arg1:string):Promise<Array<main.EvidenceFact>>;

export function ListSourceSections(arg1:number):Promise<Array<main.SourceSection>>;

export function RenderSamplePDF():Promise<main.RenderPDFResult>;

export function SaveAPIKey(arg1:main.SaveAPIKeyInput):Promise<main.ToolStatus>;

export function SaveCandidateProfile(arg1:main.CandidateProfile):Promise<main.CandidateProfile>;

export function SaveSettings(arg1:main.SaveSettingsInput):Promise<main.Settings>;

export function TestLLM():Promise<main.LLMTestResult>;

export function UpdateEvidenceFactReview(arg1:main.UpdateEvidenceFactReviewInput):Promise<main.EvidenceFact>;

export function UpdateSourceSection(arg1:main.UpdateSourceSectionInput):Promise<main.SourceSection>;
